### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: Konfigurowanie, wdrażanie i uruchamianie na platformie Azure
metadata:
  title: Konfigurowanie, wdrażanie i uruchamianie na platformie Azure
  description: Konfigurowanie, wdrażanie i uruchamianie na platformie Azure
  ms.openlocfilehash: 2877e343b38fce7016c15621f390db6343838e7d
  ms.sourcegitcommit: 12b4711682dac42f742a944fd9baa0e9dd09cf35
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 08/22/2018
  ms.locfileid: "40447025"
durationInMinutes: 10
interactive: bash
content: '[!include[](includes/6-configure-deploy-run-azure.md)]'
