### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: Konfigurowanie, wdrażanie i uruchamianie na platformie Azure
metadata:
  title: Konfigurowanie, wdrażanie i uruchamianie na platformie Azure
  description: Konfigurowanie, wdrażanie i uruchamianie na platformie Azure
  ms.openlocfilehash: 12d10497be5490db01c1822d11cd81f3145588f5
  ms.sourcegitcommit: 926510a198d738c5726081f6d7994fe9b6fc6edb
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43179951"
durationInMinutes: 12
interactive: bash
content: '[!include[](includes/6-configure-deploy-run-azure.md)]'
