### YamlMime:ModuleUnit
uid: learn.store-app-data-with-azure-blob-storage.5-configure-and-initialize-the-client-library
title: Konfigurowanie i inicjowanie biblioteki klienta
metadata:
  title: Konfigurowanie i inicjowanie biblioteki klienta
  description: Konfigurowanie i inicjowanie biblioteki klienta
  ms.openlocfilehash: c7cc43321a9dc94f71e7689a47ca31e8fe7c774c
  ms.sourcegitcommit: 12b4711682dac42f742a944fd9baa0e9dd09cf35
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 08/22/2018
  ms.locfileid: "40443822"
durationInMinutes: 10
interactive: bash-editor
content: '[!include[](includes/5-configure-and-initialize-the-client-library.md)]'
